apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: backend
        app: backend
    spec:
      containers:
        - name: dttt-backend
          image: dttt/backend
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 64Mi
          env:
            - name: app
              value: "backend"
            - name: nats
              value: "nats://192.168.88.26:4222"